### ISSUE TITLE
Upgrade from 1.15 to 1.16 fails

### ISSUE THREAD

**Issue by lightdot** [billthefarmer/tuner#19]
Stock Android 6.0 on LG V10, upgrade from 1.15 to 1.16 from F-droid fails with:

Error installing Tuner
Failed to install due to an unknown error

Tried clearing the app cache and data before repeating the upgrade, same result. I noticed I had to re-add the right to use the microphone manually afterwards (can't recall if it was the same when I installed the app originally, or did it ask for it), but baring that, the 1.15 continues to work properly.

This is probably not a very detailed bug report, if there is more data I can provide in regards to the actual upgrade error, please point me in the right direction...

**Comment by billthefarmer** [comment]
Yes that happens on android 6, but not on 4.4, or 5.1. It may be because I changed the target api version. The same thing happens with my scope app. The solution is to uninstall it and install the latest version. You will lose the settings, but you lose them if you clear the data. See https://github.com/billthefarmer/scope/issues/11.

**Comment by lightdot** [comment]
Confirmed, uninstall and reinstall worked for me. Thanks!
