### ISSUE TITLE
[idea] show note on staff

### ISSUE THREAD

**Issue by strk** [billthefarmer/tuner#25]
I've been thinking that it would be useful to see the note I'm playing with my trumpet on a (transposed) staff, which sounds something not that sci-fi to implement, maybe as part of an existing tuner (like this) or maybe as a separate app, what do you think, too crazy ?

It's that with the trumpet I never know where in the overtone series I am :)

**Comment by billthefarmer** [comment]
I have implemented this, it will be in the next version.

![screenshot_20190112-164737](https://user-images.githubusercontent.com/3448386/51085673-92320280-1734-11e9-8792-d1743e33551e.png)

**Comment by strk** [comment]
Great news, thanks !

**Comment by strk** [comment]
Maybe though the staff could be bigger ? Maybe omitting the detail above (I would think one would want to know either details OR rough staff)

**Comment by billthefarmer** [comment]
The staff range is from D2 to B5. I used this diagram from [Wikipedia](https://en.wikipedia.org/wiki/Clef) for reference. I included the leger lines at top and bottom to match the one in the middle and so the treble clef doesn't go off the top.

![Clef diagram](https://upload.wikimedia.org/wikipedia/commons/7/73/Clef_Diagram.png)

**Comment by strk** [comment]
I meant bigger in size, not in range. For readability. The use case I had in mind was putting a score and your phone one near the other and check on the phone if you are hitting the right notes on the score :)
It would probably help to be able to configure which octave the staff represents, rather than being strictly canonical as wikipedia documents (and think about transposing instruments too..) - I guess it could also be nice to be able to specify the signature key, to reduce accidentals noise :)

**Comment by billthefarmer** [comment]
It's possible to make it a bit bigger - the same size as the meter, which I have done. However bear in mind that the primary [advertised](https://github.com/billthefarmer/tuner/blob/master/README.md) purpose of this app is an accordion tuner. That's why it has the spectrum display that can show multiple reeds. Some parts, like the strobe and the staff are extras that don't distract from that. All the enhancements that I have added either extend that purpose or, as I said, don't distract from it.

However, I have designed the code of this app so that it can display any combination of the various views without code changes, provided the aspect ratio doesn't change too much. That's why in landscape it can just have the display and the meter with the code just not using the views not present.

Therefore it would be fairly trivial to clone it and produce a customised version with any combination of views.

> Your mission, should you accept it it to produce a clone with the views that **you** want. ;-)

**Comment by billthefarmer** [comment]
It's also possible, if you are using LineageOS or something similar, to set up expanded desktop for an individual app to get rid of the status bar and navigation bar, making the app that bit bigger. I do that for all my screenshots on here.

**Comment by strk** [comment]
Ehm... I just lost (soft?briked) a LineageOS after 2 months, so this
is a sensible spot. I'd love to move on with my skill-building for
mobile apps, and this is a great app to use for that.

It would be great to find build instructions in that README :)

**Comment by strk** [comment]
I finally tried it, it is GREAT !

I love your work Bill :)
