### ISSUE TITLE
V1.38 now confused by electric bass? 

### ISSUE THREAD

**Issue by m0d0nne11** [billthefarmer/tuner#45]
Occasional use of the tuner app in the past several years with my electric bass and small amplifier worked very well, correctly identifying the notes of open strings as well as harmonics and fretted notes. But FYI with the recent version 1.38 it now insists on identifying my (correctly tuned) open D string as F#1 +.29 and it will similarly misidentify that same D note when sounded on the adjacent A string. Executing on a stock Moto G4.

**Comment by billthefarmer** [comment]
That's interesting. I haven't made any changes to the audio part of this app for two years, and that was to add different temperaments. If you don't need the added translations or custom temperaments you can use an older version. Some are on [F-Droid](https://f-droid.org/packages/org.billthefarmer.tuner/), and more [here](https://github.com/billthefarmer/tuner/releases).

**Comment by m0d0nne11** [comment]
I should also mention that coincident with this misbehavior is the fact that I recently replaced my strings with some new-in-package RotoSound Swing Bass (discovered in a closet) that were purchased no later than 1983.  They sound gorgeous, ringing like a piano, but maybe that's a problem?

**Comment by m0d0nne11** [comment]
Hmmm, the 1.36 behaves identically, so I guess the problems are at my end, largely.  I wonder if present-day RotoSound strings are manufactured the same as these relics; even as a starving student I adored their bright metallic sound (enough to pay stooopidly high prices for these Brit strings here in the US) but maybe they generate enough overtones/harmonics to keep your algorithms from finding the fundamental.  Anyway, thanks and keep up the good work!

**Comment by billthefarmer** [comment]
Although I do have an acoustic guitar which I noodle on occasionally, I don't use this app for tuning it or my banjo. All the musicians I know who play string instruments use those small clip on tuners. I designed this app primarily for tuning free reed instruments like accordions so that you can tune multiple reeds at the same time. You are probably making life unnecessarily difficult using this app, there are plenty of free tuner apps designed for tuning guitars, etc, out there.
